Initialization
Duvan0902/promotoraapp pull request #1
Opened 2020-12-02 18:54 UTC by Duvan0902

2020-12-14 20:40 UTC, sdtorresl requested changes

2020-12-14 20:40 UTC, sdtorresl commented on lib/Common/contacts_management.dart
> +          na = widget.name;
Usa mejores nombres de variables, deben ser entendibles.

2020-12-14 20:40 UTC, sdtorresl commented on lib/Common/fab_button_app_bar.dart
> +class FABBottomAppBarItem {
Esta clase se usaba para hacer la barra de abajo de la app de ICFES; sin embargo, no es necesario tener todo esto para hacer la barra de navegación que se necesita en esta app. Creo que hay varias cosas que pueden sobrar.

2020-12-14 20:40 UTC, sdtorresl commented on lib/bloc/provider_bloc.dart
> +  static Provider _instancia;
Esto está en español

2020-12-14 20:40 UTC, sdtorresl commented on lib/provider/contacts_provider.dart
> +  final String _url = "http://66.228.51.95:1337/contactos";
Recuerda usar un archivo de configuración para extraer la URL base de la API, igual que en ICFES. Esto hará más sencillo el paso a producción.

2020-12-14 20:40 UTC, sdtorresl commented on pubspec.yaml
> +  flutter_localizations: # Add this line
¿Para qué añadiste esta dependencia?

2020-12-14 20:46 UTC, Duvan0902 commented on pubspec.yaml
> +  flutter_localizations: # Add this line
La dependencia se añadio para cambiar el idioma del calendario.

2020-12-14 20:50 UTC, Duvan0902 commented on lib/Common/contacts_management.dart
> +          na = widget.name;
se hizo la debida corrección de los nombres

2020-12-30 19:24 UTC, Duvan0902 commented on lib/bloc/provider_bloc.dart
> +  static Provider _instancia;
Se hizo el debido cambio de idioma

2020-12-30 20:38 UTC, Duvan0902 commented on lib/provider/contacts_provider.dart
> +  final String _url = "http://66.228.51.95:1337/contactos";
Se realizo la configuración correspondiente para la extracción  de la URL base de la API

2021-01-16 20:41 UTC, merged